name: Expo Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm install -g expo-cli
      - run: npm install
      - run: expo login -u ${{ secrets.weldetsadik2535@gmail.com }} -p ${{ secrets.Mekdes22@B }}
      - run: expo publish